Download files
Grapheene/grapheene-node pull request #9
Opened 2022-03-08 00:49 UTC by matt2695

Added files downloads

2022-03-08 01:01 UTC, nabeards commented on src/lib/DatabaseGenerator.ts
> +            try {
I say wrap the entire `if` statement in a try/catch, and then provide a better console.error message, like `Unable to prepare ${options.dbProvider} database: ${e.message}`

2022-03-08 01:02 UTC, nabeards requested changes
Left a comment about the try/catch in DatabaseGenerator.ts
Also just need to run `npm run patch-version` to bump and tag it now.

2022-03-08 14:19 UTC, matt2695 commented on src/lib/DatabaseGenerator.ts
> +            try {
updated take a look

2022-03-14 18:27 UTC, closed without merging

2022-03-15 02:56 UTC, nabeards commented
Will you be opening a new PR with this and the changes you mentioned to load small files into memory?